### ISSUE TITLE
Crashes on lsp-mode with version 0.5.4

### ISSUE THREAD

**Issue by joefbsjr** [razzmatazz/csharp-language-server#44] opened 2022-08-23 13:21 UTC
After updating to 0.5.4 csharp-ls crashes not long after initialization. 

I don't know where to get a log, so if you need one please tell me where I can find it. The only error I get in stderr is `Process csharp-ls stderr<1> finished`

It crashes while moving the cursor, so my suspicion are either highlight or documentation.

**Comment by razzmatazz** [comment] 2022-08-23 13:22
hey; I am tripping on this as well, debugging why -- will release a new version asap

**Comment by razzmatazz** [comment] 2022-08-23 13:40
the cause is apparently this:
- https://github.com/ionide/LanguageServerProtocol/commit/114bd9c5ffbb238965bbb3e2d8c0ca4bf83b2a5f

I am just trying to find a a way to avoid reverting this on the upstream and just fix csharp-ls with try/with in right places :)

**Comment by razzmatazz** [comment] 2022-08-23 14:07
I have added this commit: 06411285b76b46d2fc4b9f8e30e510354dd528e7 but not 100% that fixes it all

**Comment by razzmatazz** [comment] 2022-08-23 14:08
@joefbsjr if you could test if that fix work it would be really nice

because it does not hit it for me at once, it takes some incantation of requests to trigger the crash.. for some reason, so I am reluctant to declare victory yet :)

**Comment by joefbsjr** [comment] 2022-08-23 14:17
Sure. Will try later today.

**Comment by razzmatazz** [comment] 2022-08-23 14:36
uh.. actually the error is in upstream Ionide.LSP -- it marks LocalRpcException as fatal, but we use it to report "error" lsp results.. ok, attempt no 2

**Comment by razzmatazz** [comment] 2022-08-23 14:50
Upstream Ionide.LSP PR:
- https://github.com/ionide/LanguageServerProtocol/pull/33

**Comment by razzmatazz** [comment] 2022-08-23 15:22
0.5.5 released that should fix this (I very much hope so):
- https://www.nuget.org/packages/csharp-ls/0.5.5

**Comment by razzmatazz** [comment] 2022-08-26 19:46
Closing, @joefbsjr please reopen if this occurs again

**Closed by razzmatazz** 2022-08-26 19:46 UTC
