### ISSUE TITLE
Version 0.12.0 high resource usage and slow autocomplete

### ISSUE THREAD

**Issue by DanielViberg** [razzmatazz/csharp-language-server#151] opened 2024-04-22 14:30 UTC
Hello,

Nice job on this c-sharp server.

Since version 0.12.0 i'm seeing high cpu usage and slow auto complete:
![image](https://github.com/razzmatazz/csharp-language-server/assets/27137435/283ee119-e8d8-433a-aff3-d4d4be49d4d6)
The machine is a windows 10 64bit, running vim in powershell.
If i downgrade to version 0.11.0 the problem disappears.

**Comment by razzmatazz** [comment] 2024-04-24 05:24
Hey @DanielViberg 

Could you try backing out this commit: https://github.com/razzmatazz/csharp-language-server/commit/ada53cd7457b08e1c69bfc979370ca20120e9bd8 and then recompile from source?

It can be either this commit (roslyn upgrade) or something else–it may be time to add option to dump request stats to stderr to find which endpoint in particular is slow.

**Comment by AbrA-K** [comment] 2024-04-24 15:05
Have the same issue (where version 0.11.0 was a LOT faster).
I have trouble building building the lsp for testing this. ``dotnet build`` on the Project root will build it and the binary will be in ``<Projectroot>/src/CSharpLanguageServer/bin/Debug/net8.0/CSharp/Language/Server``, correct?
(another thing: I'm using the dotnet-sdk-8.0.104 and not 8.0.200 - this should not be a big deal, right?)

**Comment by DanielViberg** [comment] 2024-04-26 14:32
Im currenly not near my dev machine. I'll get back to you as soon as i get back!

**Comment by DmitryHudrich** [comment] 2024-04-28 15:48
Hi, i have same problem and i compiled lsp from last commit. i just replaced roslyn version to 4.7.0, but the problem still remains so i think the problem is not roslyn

**Comment by DmitryHudrich** [comment] 2024-04-28 16:31
[a117ea](https://github.com/razzmatazz/csharp-language-server/commit/a117eafd6f2fa49864f8b8027e6ee1633a990599) is the commit that caused the problem. everything works fine before him.
lsp already supports the twelfth version of the language here, but I don't see any performance problems.

**Comment by razzmatazz** [comment] 2024-05-01 06:37
> [a117ea](https://github.com/razzmatazz/csharp-language-server/commit/a117eafd6f2fa49864f8b8027e6ee1633a990599) is the commit that caused the problem. everything works fine before him. lsp already supports the twelfth version of the language here, but I don't see any performance problems.

Thank you for triaging this! I will investigate this further

**Comment by razzmatazz** [comment] 2024-05-01 07:08
Should be fixed in https://github.com/razzmatazz/csharp-language-server/commit/f6ce28555649f97fc66f5fda6f9d627bb6b5b529

Will release a new version later this week.

**Comment by j0of** [comment] 2024-05-07 20:58
Has this issue been resolved for anyone yet? I am also having this problem but I'm unsure if the patch has already been released

**Comment by razzmatazz** [comment] 2024-05-08 05:17
> Has this issue been resolved for anyone yet? I am also having this problem but I'm unsure if the patch has already been released

I did not release a bugfix release yet -- trying to figure out if I can make it even faster by disabling autocomplete from non-imported namespaces.

**Closed** 2024-06-03 19:39 UTC
